### ISSUE TITLE
Where to download dataset AMASS

### ISSUE THREAD

**Issue by zhangsanfeng86** [naver/PoseGPT#1]
Hi , 
Thank your for release!

Where to down load dataset AMASS?

**Comment by fabienbaradel** [comment]
Hi,
You can download AMASS here: https://amass.is.tue.mpg.de/

Le mar. 25 oct. 2022, 11:53, zhangsanfeng86 ***@***.***> a
écrit :

**Comment by zhangsanfeng86** [comment]
> https://amass.is.tue.mpg.de/

Thank you :)
